### PR TITLE
Deserialize empty location fields as None

### LINKED ISSUE #80: Image metadata issues
When saving image description, the `name` and `description` are ignored, while `latitude `and `longitude `get saved even if they are an empty string. The back-end should only save `lat `& `long `if they have a number value and the value is not 0.

image

The reason this causes issues is that the front-end expects the `location` object to only appear if it has values.

### PR DESCRIPTION
**Pull request by Jokler**
Unless @dolanske can still reproduce the other problems this resolves #80.

### CODE REVIEW

**Comment by dolanske** [comment]
I can only test this if we merge it, so LGTM?

**Comment by Jokler** [comment]
My intention was that you would check if #80 would be fully resolved by adjusting how the location is stored.

**Comment by dolanske** [comment]
I think I understood the issue. The reason the `fileName` was not updating was because I was using the original image filename, not the metadata endpoint for said image. I did test things now and in both cases my changes were saved for the `metadata` endpoint. 

Makes me wonder though, should they also be reflected for the original image object? Because in that case, they are not being saved. `fileName` is still the original upload, unless that is the desired outcome of course.

**Review by dolanske — APPROVED** [review]
LGTM

**Comment by Jokler** [comment]
I'll just merge this and close #80, in case there are still problems another issue can be opened.

**Pull request merged**
